AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template will create the needed databases in the RDS for use by XL JetPack
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - DataSubnet1ID
          - DataSubnet2ID
      - Label:
          default: Database Configuration
        Parameters:
          - DBHost
          - DBUsername
          - DBPassword
          - RDSSecurityGroup
  ParameterLabels:
    DataSubnet1ID:
      default: Data subnet 1
    DataSubnet2ID:
      default: Data subnet 2
    DBPassword:
      default: Database administrator password
    DBUsername:
      default: Database administrator username
    DBHost:
      default: Database host
    RDSSecurityGroup:
      default: RDS Security Group
Parameters: 
  DataSubnet1ID:
    Description: The first subnet the Aurora database cluster should be deployed to
    Type: AWS::EC2::Subnet::Id
  DataSubnet2ID:
    Description: The second subnet the Aurora database cluster should be deployed to
    Type: AWS::EC2::Subnet::Id
  DBUsername:
    Description: The Postgres DB username
    Type: String
  DBPassword:
    Description: The Postgres DB Password
    Type: String
    NoEcho: True
  DBHost:
    Description: The Postgres DB Host/Endpoint
    Type: String
  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Description: The security group that grants access to the RDS

# Mappings: 
# Conditions: 

Resources:
  RDSCreateDBLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  https://s3.amazonaws.com/xl-jetpack-aws/rds/rds-lambda.yaml
      Parameters:
        AuroraSubnets: !Join [ ',', [ !Ref DataSubnet1ID, !Ref DataSubnet2ID ]]
        DBUser: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DBHost: !Ref DBHost
        AuroraRDSSecurityGroup: !Ref RDSSecurityGroup
#Outputs:
