AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template will setup RDS including the databases for use by XL JetPack
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
          - DataSubnetIDs
          - PrivateSubnetID
      - Label:
          default: Database Configuration
        Parameters:
          - DBInstanceClass
          - DBMasterUsername
          - DBMasterPassword
          - DBBackupRetentionPeriod
    ParameterLabels:
      VPCID:
        default: VPC ID
      DataSubnetIDs:
        default: Data subnets
      PrivateSubnetID:
        default: Private subnet
      DBMasterPassword:
        default: Database administrator password
      DBMasterUsername:
        default: Database administrator username
      DBInstanceClass:
        default: Database instance class
      DBBackupRetentionPeriod:
        default: Database backup retention period
Parameters: 
  VPCID:
    Description: The VPC Id
    Type: AWS::EC2::VPC::Id
  DataSubnetIDs:
    Description: The subnets the Aurora database cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnetID:
    Description: "The private subnet the AWS Lambda function should be deployed to (NOTE: Required internet access)"
    Type: AWS::EC2::Subnet::Id
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: xladmin
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMasterPassword:
    AllowedPattern: "(?=\\S)[^@/\"\\r\\n\\t\\f\\s]*"
    ConstraintDescription: 'Min 8 alphanumeric. Cannot contain white space, @, /, "'
    Description: The database admin account password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: True
    Type: String
  DBInstanceClass:
    AllowedValues:
      - db.r4.16xlarge
      - db.r4.8xlarge
      - db.r4.4xlarge
      - db.r4.2xlarge
      - db.r4.xlarge
      - db.r4.large
    ConstraintDescription: Must select a valid database instance type.
    Default: db.r4.large
    Description: The name of the compute and memory capacity class of the DB instance.
    Type: String
  DBBackupRetentionPeriod:
    Default: '7'
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String

# Mappings: 
# Conditions: 

Resources:
  RDSSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/xl-jetpack-aws/rds/rds-securitygroup.yaml
      Parameters:
        EnvironmentName: xl-jetpack
        VPCID: !Ref VPCID
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/xl-jetpack-aws/rds/rds.yaml
      Parameters:
        Subnets: !Join [ ",", !Ref DataSubnetIDs ]
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterPassword: !Ref DBMasterPassword
        DBInstanceClass: !Ref DBInstanceClass
        AuroraRDSSecurityGroup: !GetAtt RDSSecurityGroupStack.Outputs.RDSSecurityGroup
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
  RDSCreateDBLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  https://s3.amazonaws.com/xl-jetpack-aws/rds/rds-lambda.yaml
      Parameters:
        PrivateSubnets: !Ref PrivateSubnetID
        DBUser: !Ref DBMasterUsername
        DBPassword: !Ref DBMasterPassword
        DBHost: !GetAtt RDSStack.Outputs.AuroraEndPointAddress
        AuroraRDSSecurityGroup: !GetAtt RDSSecurityGroupStack.Outputs.RDSSecurityGroup

Outputs:
  RDSSecurityGroup:
    Description: The provisioned RDS SecurityGroup
    Value: !GetAtt RDSSecurityGroupStack.Outputs.RDSSecurityGroup
  AuroraEndPointAddress:
    Description: Aurora Cluster Endpoint address to connect to
    Value: !GetAtt RDSStack.Outputs.AuroraEndPointAddress
  AuroraEndPointPort:
    Description: Aurora Cluster Endpoint port to connect to
    Value: !GetAtt RDSStack.Outputs.AuroraEndPointPort